#!/bin/sh

check_hciconfig() {
	if command -v hciattach &> /dev/null; then
		if lsmod | grep -q "aic8800_fdrv"; then
			echo "hciattach -s 1500000 /dev/ttyS1 any 1500000 flow nosleep&"
			echo "Will not start hciattach, as it may cause issues with the Bluetooth module. Please start it manually if needed."
			sleep 2
			if hciconfig -a | grep -q "hci0"; then
				echo "hciconfig hci0 up&"
				echo "Will not start hciconfig, as it may cause issues with the Bluetooth module. Please start it manually if needed."
			else
				echo "hci0 not found or not available."
			fi
      ifconfig wlan0 up && udhcpc -i wlan0 > /dev/null 2>&1
		else
			echo "aic8800_fdrv not found."
		fi
	fi
}

case $1 in
	start)
		check_hciconfig &
		;;
	*)
		exit 1
		;;
esac

